"""``donkey init``: bootstrap a commented ``.donkey-kit.toml`` (config resolution)."""

from __future__ import annotations

import json
from pathlib import Path

import typer

from ..core.config import LOCAL_TOML_NAME, TOML_NAME, TRUST_PROJECT_CONFIG_ENV, DonkeyConfig
from ..core.endpoints import ALLOW_HTTP_ENV
from ._app import app

__all__ = ["init"]


# Config fields written to .donkey-kit.toml, grouped with a header comment.
# SECRETS ARE DELIBERATELY ABSENT — see _SECRET_FIELDS. This list is
# non-secret connection config only.
_INIT_GROUPS: tuple[tuple[str, tuple[str, ...]], ...] = (
    (
        "Anypoint control plane (registry)",
        ("client_id", "org_id", "environment", "region", "base_url"),
    ),
    (
        "LLM proxy (data plane) — a SEPARATE credential from the control plane",
        ("llm_proxy_url", "llm_proxy_client_id"),
    ),
    (
        "Attribution",
        ("application_name", "business_group"),
    ),
)

# Written NEVER — as commented placeholders only. A committed config file is
# the wrong home for a secret (config resolution); these belong in a gitignored
# .donkey-kit.local.toml (which the SDK overlays on this file) or in env vars.
_SECRET_FIELDS: tuple[tuple[str, str], ...] = (
    ("client_secret", "ANYPOINT_CLIENT_SECRET"),
    ("llm_proxy_client_secret", "DONKEY_LLM_PROXY_CLIENT_SECRET"),
    ("llm_proxy_key", "DONKEY_LLM_PROXY_KEY"),
)


def _toml_str(value: str) -> str:
    """Render a TOML basic string, escaping the two characters that matter."""
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _collect_missing(config: DonkeyConfig) -> list[str]:
    """Every missing required field across BOTH capabilities, in one list —
    reusing ``DonkeyConfig.missing_fields`` (what ``validated`` reports) as the
    single source of truth for what is required (config resolution), rather than
    duplicating the field set here."""
    return [item for need in ("control_plane", "llm") for item in config.missing_fields(need=need)]


def _render_toml(config: DonkeyConfig, missing: list[str]) -> str:
    """Hand-render a commented ``.donkey-kit.toml`` from resolved, non-secret
    values. No dependency on a TOML *writer*; the reader (`tomllib`) is enough."""
    lines: list[str] = [
        f"# {TOML_NAME} — generated by `donkey init` from your current environment.",
        "# Review before committing. Resolution order at runtime: values set in",
        f"# code → env → {LOCAL_TOML_NAME} → this file → defaults (config resolution).",
        "#",
        f"# SECRETS ARE NEVER WRITTEN HERE. Put them in a gitignored {LOCAL_TOML_NAME}",
        "# next to this file (same [donkey] table), or in environment variables:",
    ]
    for field, envvar in _SECRET_FIELDS:
        lines.append(f"#   - {field:<24} → env {envvar}")
    lines += [
        "#",
        "# A base_url or llm_proxy_url set here (localhost included) only receives",
        f"# credentials from this file or {LOCAL_TOML_NAME}. If your credentials are",
        "# in environment variables, set the URL there too (ANYPOINT_BASE_URL /",
        f"# DONKEY_LLM_PROXY_URL), or set {TRUST_PROJECT_CONFIG_ENV}=1 to trust this",
        "# directory's config files.",
        "#",
        "# URLs must use https://. Plain http:// is accepted for localhost; for other",
        f"# hosts only with {ALLOW_HTTP_ENV}=1 in the environment (not in this file).",
    ]
    if missing:
        lines += [
            "#",
            "# Still missing (set these before the SDK can reach the platform):",
        ]
        lines += [f"#   - {item}" for item in missing]
    lines += ["", "[donkey]"]
    for header, group_fields in _INIT_GROUPS:
        emitted = [
            (name, getattr(config, name))
            for name in group_fields
            if getattr(config, name) is not None
        ]
        if not emitted:
            continue
        lines.append(f"# {header}")
        for name, value in emitted:
            lines.append(f"{name} = {_toml_str(str(value))}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


@app.command()
def init(
    ctx: typer.Context,
    force: bool = typer.Option(
        False, "--force", help="Regenerate even if the file already exists."
    ),
) -> None:
    """Bootstrap a commented ``.donkey-kit.toml`` from the resolved config (config resolution).

    Writes every non-secret value already visible via kwargs/env/toml, and names
    EVERY missing required field at once — reusing the same
    ``DonkeyConfig.validated`` report the SDK uses at runtime, so ``init`` never
    disagrees with a live call about what is required. Secrets are never written
    (they surface as commented ``env`` pointers). Idempotent: an existing file is
    left untouched unless ``--force`` is passed. Honors the global ``--config``
    (write target), ``--env`` (environment override), and ``--json`` flags.
    """
    opts = ctx.obj or {}
    target: Path = opts.get("config") or (Path.cwd() / TOML_NAME)
    as_json: bool = bool(opts.get("json"))

    if target.exists() and not force:
        msg = f"{target} already exists; leaving it untouched. Re-run with --force to regenerate."
        if as_json:
            typer.echo(json.dumps({"path": str(target), "written": False, "missing": []}))
        else:
            typer.secho(msg, fg="yellow")
        return

    config = DonkeyConfig.from_env()
    env_override = opts.get("env")
    if env_override:
        config = config.with_overrides(environment=env_override)

    missing = _collect_missing(config)
    content = _render_toml(config, missing)

    try:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content)
    except OSError as exc:
        typer.secho(f"Could not write {target}: {exc}", fg="red", err=True)
        raise typer.Exit(1) from exc

    if as_json:
        typer.echo(json.dumps({"path": str(target), "written": True, "missing": missing}))
        return

    typer.secho(f"Wrote {target}.", fg="green")
    if missing:
        typer.echo("\nStill missing (set before the SDK can reach the platform):")
        for item in missing:
            typer.echo(f"  - {item}")
    else:
        typer.echo("All required fields resolved.")
