"""The PR-CI constraints lock stays in sync with pyproject.toml (ADR 0007 rule 3, #948).

PR CI resolves from a committed lock: one file per `(extras, dev-group, Python
version)` combo a PR-gating `ci.yml` job actually installs
(`python/constraints/<combo>-py3.NN.txt`, generated by
`scripts/compile_constraints.py`), never a file merged across combos — a
merged file can hold a ceiling one combo's own resolve pushed past another
combo's floor (see that script's module docstring; this is what made the
very first version of this lock ship unsatisfiable files for
`[openai-agents,strands]`, `[llamaindex]`, `[adk]`, and `[crewai]`).

This offline check cannot re-run the resolver (no network in a unit test), so
it cannot by itself prove a file still installs — that needs
`scripts/compile_constraints.py --check` (recompiles every combo; an
unsatisfiable combo makes `uv pip compile` fail outright, not just produce a
diff) or an actual `pip install -c <file>` in CI. What this test catches
offline is the cheap, common failure: `_COMBOS` drifting out of sync with
either `pyproject.toml` (a direct dependency the lock has never heard of) or
`.github/workflows/ci.yml` (a job whose extras no longer match any `Combo`).
"""

from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import Any

if sys.version_info >= (3, 11):
    import tomllib
else:  # pragma: no cover - 3.10 backfill
    import tomli as tomllib

_PYTHON_ROOT = Path(__file__).resolve().parents[2]
_CONSTRAINTS_DIR = _PYTHON_ROOT / "constraints"
_WORKFLOWS_DIR = _PYTHON_ROOT.parent / ".github" / "workflows"
_CI_YAML = _WORKFLOWS_DIR / "ci.yml"
_CONSTRAINT_REF_RE = re.compile(r"constraints/([A-Za-z0-9._-]+\.txt)")
_PIN_RE = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*)==")

# requirement_name()/canonicalize() do the exact PEP 503 normalization the
# allowlist check needs (#936); reuse rather than re-implement a third time.
sys.path.insert(0, str(_PYTHON_ROOT / "scripts"))
from check_new_dependencies import requirement_name  # noqa: E402
from compile_constraints import _COMBOS, Combo  # noqa: E402


def _pyproject() -> dict[str, Any]:
    return tomllib.loads((_PYTHON_ROOT / "pyproject.toml").read_text(encoding="utf-8"))


def _extra_names(pyproject: dict[str, Any], extra: str) -> set[str]:
    """Canonical names of ``extra``'s own direct requirements, as declared."""
    raw = pyproject["project"]["optional-dependencies"][extra]
    return {requirement_name(r) for r in raw}


def _group_names(pyproject: dict[str, Any], group: str) -> set[str]:
    raw = [item for item in pyproject["dependency-groups"][group] if isinstance(item, str)]
    return {requirement_name(r) for r in raw}


def _combo_direct_names(combo: Combo, pyproject: dict[str, Any]) -> set[str]:
    """Every direct dependency ``combo``'s own install line requests."""
    names: set[str] = set()
    for extra in combo.extras:
        names |= _extra_names(pyproject, extra)
    if combo.dev_group:
        names |= _group_names(pyproject, "dev")
    for group in combo.groups:
        names |= _group_names(pyproject, group)
    return names


def _pinned_names(path: Path) -> set[str]:
    names: set[str] = set()
    for line in path.read_text(encoding="utf-8").splitlines():
        match = _PIN_RE.match(line.strip())
        if match:
            names.add(requirement_name(match.group(0).removesuffix("==")))
    return names


def test_every_combo_has_a_committed_file_for_each_of_its_python_versions() -> None:
    """Every (combo, python) pair ci.yml needs has its own constraints file.

    One file per combo, never merged — a combo's file is satisfiable for that
    combo by construction only if it was compiled for exactly that combo.
    """
    for combo in _COMBOS:
        for python_version in combo.python_versions:
            path = _CONSTRAINTS_DIR / combo.file_name(python_version)
            assert path.is_file(), (
                f"missing {path.relative_to(_PYTHON_ROOT)} for combo {combo.name!r} "
                f"({combo.covers}); run `python scripts/compile_constraints.py` from "
                "python/ (see docs/adr/0007-dependency-policy.md rule 3)"
            )


def test_every_combo_direct_dependency_is_pinned_in_its_own_file() -> None:
    """A combo's own extras/dev-group deps are pinned in its own file only.

    Unlike the old merged design, this does NOT assert every direct dependency
    in pyproject.toml is pinned in every file — a combo's file only needs to
    cover what that combo's own `pip install` line requests.
    """
    pyproject = _pyproject()
    for combo in _COMBOS:
        declared = _combo_direct_names(combo, pyproject)
        for python_version in combo.python_versions:
            path = _CONSTRAINTS_DIR / combo.file_name(python_version)
            if not path.is_file():
                continue  # reported by the previous test
            pinned = _pinned_names(path)
            missing = sorted(declared - pinned)
            assert not missing, (
                f"{path.relative_to(_PYTHON_ROOT)} (combo {combo.name!r}) is missing "
                f"pins for {missing}; run `python scripts/compile_constraints.py` from "
                "python/ to refresh (see docs/adr/0007-dependency-policy.md rule 3)"
            )


def test_constraints_files_pin_exact_versions_only() -> None:
    """Every non-comment, non-blank line is a `name==version` pin, nothing looser.

    A constraints file is supposed to make PR CI reproducible; a `>=` or an
    unpinned line here would silently reintroduce the fresh-resolve drift ADR
    0007 rule 3 exists to remove.
    """
    paths = sorted(_CONSTRAINTS_DIR.glob("*.txt"))
    assert paths, f"no constraints files found under {_CONSTRAINTS_DIR}"
    for path in paths:
        for line in path.read_text(encoding="utf-8").splitlines():
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            assert _PIN_RE.match(stripped), f"{path.name}: not an exact pin: {stripped!r}"


def test_every_committed_file_belongs_to_a_combo() -> None:
    """No orphaned constraints file: every committed file maps back to a `Combo`.

    Catches the opposite drift from the other tests: a job's extras changed
    (or a job was removed) so its old `-c` file no longer corresponds to
    anything in `_COMBOS`, and nobody deleted it.
    """
    expected = {
        combo.file_name(python_version)
        for combo in _COMBOS
        for python_version in combo.python_versions
    }
    actual = {path.name for path in _CONSTRAINTS_DIR.glob("*.txt")}
    orphaned = sorted(actual - expected)
    assert not orphaned, (
        f"constraints/ has files no Combo in scripts/compile_constraints.py "
        f"covers: {orphaned}; either add the Combo or delete the file"
    )


def test_adapter_contract_matrix_extras_each_have_their_own_combo() -> None:
    """Every ci.yml `adapter-contract` matrix leg maps to a `Combo` by name.

    That job's `-c` flag is `constraints/adapter-contract-${DONKEY_CONTRACT_EXTRA}-
    py3.12.txt`, so each matrix `extra` value must have a matching
    `adapter-contract-<extra>` Combo, or that leg's install step 404s on a
    nonexistent file.
    """
    ci_yaml = _CI_YAML.read_text(encoding="utf-8")
    pattern = r"adapter-contract:.*?matrix:\s*\n\s*extra:\s*\n((?:\s*-\s*\S+\n)+)"
    match = re.search(pattern, ci_yaml, re.DOTALL)
    assert match, "could not find adapter-contract's matrix.extra list in ci.yml"
    matrix_extras = re.findall(r"-\s*(\S+)", match.group(1))
    assert matrix_extras, "adapter-contract's matrix.extra list parsed empty"
    combo_names = {combo.name for combo in _COMBOS}
    for extra in matrix_extras:
        expected_combo = f"adapter-contract-{extra}"
        assert expected_combo in combo_names, (
            f"ci.yml adapter-contract matrix has extra {extra!r} but "
            f"scripts/compile_constraints.py has no Combo named {expected_combo!r}"
        )


def test_every_constraints_file_a_workflow_names_exists() -> None:
    """A `constraints/<file>.txt` a workflow installs from is committed (#763).

    Templated names (`test-py${PYTHON_VERSION}.txt`) are not matched by the
    pattern; the per-combo tests above cover those.
    """
    for workflow in sorted(_WORKFLOWS_DIR.glob("*.yml")):
        for name in _CONSTRAINT_REF_RE.findall(workflow.read_text(encoding="utf-8")):
            assert (_CONSTRAINTS_DIR / name).is_file(), (
                f"{workflow.name} installs from constraints/{name}, which is not "
                "committed; add its Combo and run `python scripts/compile_constraints.py`"
            )


def test_every_dist_build_uses_the_locked_release_toolchain() -> None:
    """Each `python -m build` step builds with the locked backend (#763).

    `python -m build` alone builds in an isolated env with whatever hatchling
    is newest that day. `--no-isolation` makes it use the hatchling the job
    installed from constraints/release-py3.11.txt, and the same step must
    install from that file.
    """
    seen = 0
    for workflow in sorted(_WORKFLOWS_DIR.glob("*.yml")):
        for step in re.split(r"\n\s*- ", workflow.read_text(encoding="utf-8")):
            commands = [
                line.strip()
                for line in step.splitlines()
                if line.strip() and not line.strip().startswith("#")
            ]
            for build in (c for c in commands if "python -m build" in c):
                seen += 1
                assert "--no-isolation" in build, (
                    f"{workflow.name}: `{build}` builds in an isolated env, so it "
                    "ignores the locked hatchling; add --no-isolation"
                )
                assert any(
                    "pip install" in c and "-c constraints/release-py3.11.txt" in c
                    for c in commands
                ), (
                    f"{workflow.name}: the step running `{build}` does not install "
                    "its toolchain with -c constraints/release-py3.11.txt"
                )
    assert seen >= 3, "expected the publish-pypi, publish-testpypi and base-only builds"
