"""The PR-CI constraints lock stays in sync with pyproject.toml (ADR 0007 rule 3, #948).

PR CI resolves from a committed lock (``python/constraints/py3.*.txt``,
generated by ``scripts/compile_constraints.py``), so a PR's result does not
change when an upstream package releases between the branch being cut and CI
running. This offline check cannot re-run the resolver (no network in a unit
test), but it catches the cheap, common failure: a direct dependency declared
in ``pyproject.toml`` that the lock has never heard of — e.g. a new extra or a
new dev-group package added without a ``scripts/compile_constraints.py``
refresh. A real version drift (an existing pin going stale) is caught by CI
actually installing with ``-c`` and by ``scripts/compile_constraints.py
--check`` (not run here — it shells out to ``uv`` and PyPI).
"""

from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import Any

if sys.version_info >= (3, 11):
    import tomllib
else:  # pragma: no cover - 3.10 backfill
    import tomli as tomllib

_PYTHON_ROOT = Path(__file__).resolve().parents[2]
_CONSTRAINTS_DIR = _PYTHON_ROOT / "constraints"
_PIN_RE = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*)==")

# canonicalize() from scripts/check_new_dependencies.py (#936) does the exact
# same PEP 503 normalization the allowlist check needs; reuse it rather than
# re-implementing name canonicalization a third time.
sys.path.insert(0, str(_PYTHON_ROOT / "scripts"))
from check_new_dependencies import canonicalize, declared_names  # noqa: E402


def _pyproject() -> dict[str, Any]:
    return tomllib.loads((_PYTHON_ROOT / "pyproject.toml").read_text(encoding="utf-8"))


def _constraints_files() -> list[Path]:
    files = sorted(_CONSTRAINTS_DIR.glob("py3.*.txt"))
    assert files, f"no constraints files found under {_CONSTRAINTS_DIR}"
    return files


def _pinned_names(path: Path) -> set[str]:
    names: set[str] = set()
    for line in path.read_text(encoding="utf-8").splitlines():
        match = _PIN_RE.match(line.strip())
        if match:
            names.add(canonicalize(match.group(1)))
    return names


def test_constraints_dir_has_one_file_per_matrix_python_version() -> None:
    """ci.yml's Python matrix is 3.10/3.11/3.12; the lock must cover each."""
    names = {path.name for path in _constraints_files()}
    assert names == {"py3.10.txt", "py3.11.txt", "py3.12.txt"}


def test_every_direct_dependency_is_pinned_in_every_constraints_file() -> None:
    """A dependency declared in pyproject.toml has a pin for every Python version.

    `_COMBOS` in scripts/compile_constraints.py together cover every extra and
    the dev group, so every direct dependency's canonical name must appear in
    every generated constraints/py3.*.txt. A name missing from one means
    either the lock is stale (add it to a combo and refresh) or the extra it
    lives in was dropped from every PR-gating ci.yml job (drop the combo too).
    """
    declared = declared_names(_pyproject())
    for path in _constraints_files():
        pinned = _pinned_names(path)
        missing = sorted(declared - pinned)
        assert not missing, (
            f"{path.relative_to(_PYTHON_ROOT)} is missing pins for {missing}; "
            "run `python scripts/compile_constraints.py` from python/ to refresh "
            "(see docs/adr/0007-dependency-policy.md rule 3)"
        )


def test_constraints_files_pin_exact_versions_only() -> None:
    """Every non-comment, non-blank line is a `name==version` pin, nothing looser.

    A constraints file is supposed to make PR CI reproducible; a `>=` or an
    unpinned line here would silently reintroduce the fresh-resolve drift ADR
    0007 rule 3 exists to remove.
    """
    for path in _constraints_files():
        for line in path.read_text(encoding="utf-8").splitlines():
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            assert _PIN_RE.match(stripped), f"{path.name}: not an exact pin: {stripped!r}"
