"""Vulture whitelist: names vulture reports unused in ``src/`` that are used (#720).

The CI dead-code check (``vulture``, configured under ``[tool.vulture]`` in
pyproject.toml) reads only ``src/`` plus this file, so a symbol only the tests
use counts as dead. Vulture can't see the uses of what is listed here: the
public API a caller uses, framework and pytest hooks called by name, typer
commands, dataclass fields, keyword arguments of stubs that raise
``blocked(...)`` until their API is verified, and lazy ``__getattr__`` modules.

When vulture flags a new name, delete the code if it is dead. Add it here only
if something outside ``src/`` uses it, and keep the comment saying where it is.
Regenerate the candidate list with::

    vulture src --min-confidence 60 --make-whitelist
"""

# ruff: noqa
__getattr__  # unused function (src/donkey_kit/conformance/__init__.py)
__dir__  # unused function (src/donkey_kit/conformance/__init__.py)
_.requests_received  # unused property (src/donkey_kit/conformance/gateway.py)
_.set_scenarios  # unused method (src/donkey_kit/conformance/gateway.py)
_.should_exit  # unused attribute (src/donkey_kit/conformance/gateway.py)
pytest_addoption  # unused function (src/donkey_kit/conformance/plugin.py)
_.runtest  # unused method (src/donkey_kit/conformance/plugin.py)
style  # unused variable (src/donkey_kit/conformance/plugin.py)
_.reportinfo  # unused method (src/donkey_kit/conformance/plugin.py)
_.collect  # unused method (src/donkey_kit/conformance/plugin.py)
pytest_collection  # unused function (src/donkey_kit/conformance/plugin.py)
_.testscollected  # unused attribute (src/donkey_kit/conformance/plugin.py)
pytest_terminal_summary  # unused function (src/donkey_kit/conformance/plugin.py)
exitstatus  # unused variable (src/donkey_kit/conformance/plugin.py)
question  # unused variable (src/donkey_kit/conformance/suite.py)
_.pace  # unused method (src/donkey_kit/core/budget.py)
_.wait_for_reset  # unused method (src/donkey_kit/core/budget.py)
cost_team_header  # unused variable (src/donkey_kit/core/config.py)
cost_project_header  # unused variable (src/donkey_kit/core/config.py)
cost_env_header  # unused variable (src/donkey_kit/core/config.py)
cost_enduser_header  # unused variable (src/donkey_kit/core/config.py)
framework_error  # unused variable (src/donkey_kit/core/errors.py)
_.substituted  # unused property (src/donkey_kit/core/lastcall.py)
_.cache_hit  # unused property (src/donkey_kit/core/lastcall.py)
_.available  # unused property (src/donkey_kit/core/lastcall.py)
GEN_AI_SEMCONV_VERSION  # unused variable (src/donkey_kit/core/telemetry.py)
qualname  # unused variable (src/donkey_kit/core/toolspec.py)
docstring  # unused variable (src/donkey_kit/core/toolspec.py)
is_async  # unused variable (src/donkey_kit/core/toolspec.py)
tool_spec  # unused function (src/donkey_kit/core/toolspec.py)
_clear_registry  # unused function (src/donkey_kit/core/toolspec.py)
CORRELATION_HEADER  # unused variable (src/donkey_kit/core/transport/headers.py)
# httpx constructor options typed on the governed clients' **kw (#728).
proxy  # unused variable (src/donkey_kit/core/transport/pipeline.py)
trust_env  # unused variable (src/donkey_kit/core/transport/pipeline.py)
limits  # unused variable (src/donkey_kit/core/transport/pipeline.py)
http2  # unused variable (src/donkey_kit/core/transport/pipeline.py)
_.discover  # unused method (src/donkey_kit/donkey.py)
domain  # unused variable (src/donkey_kit/donkey.py)
locked  # unused variable (src/donkey_kit/donkey.py)
_.lock  # unused method (src/donkey_kit/donkey.py)
langgraph  # unused variable (src/donkey_kit/donkey.py)
adk  # unused variable (src/donkey_kit/donkey.py)
strands  # unused variable (src/donkey_kit/donkey.py)
agent_framework  # unused variable (src/donkey_kit/donkey.py)
openai_agents  # unused variable (src/donkey_kit/donkey.py)
crewai  # unused variable (src/donkey_kit/donkey.py)
llamaindex  # unused variable (src/donkey_kit/donkey.py)
_.last_call  # unused property (src/donkey_kit/donkey.py)
conformance_tested  # unused variable (src/donkey_kit/integrations/__init__.py)
_.policy_middleware  # unused method (src/donkey_kit/integrations/agent_framework.py)
_.framework_error  # unused attribute (src/donkey_kit/integrations/agent_framework.py)
_.on_inbound  # unused method (src/donkey_kit/integrations/crewai.py)
_.aon_outbound  # unused method (src/donkey_kit/integrations/crewai.py)
_.aon_inbound  # unused method (src/donkey_kit/integrations/crewai.py)
run_inline  # unused variable (src/donkey_kit/integrations/langgraph.py)
_.on_chat_model_start  # unused method (src/donkey_kit/integrations/langgraph.py)
serialized  # unused variable (src/donkey_kit/integrations/langgraph.py)
messages  # unused variable (src/donkey_kit/integrations/langgraph.py)
_.on_llm_end  # unused method (src/donkey_kit/integrations/langgraph.py)
_.on_llm_error  # unused method (src/donkey_kit/integrations/langgraph.py)
_.framework_error  # unused attribute (src/donkey_kit/integrations/langgraph.py)
function_calling  # unused variable (src/donkey_kit/llm/catalog.py)
vision  # unused variable (src/donkey_kit/llm/catalog.py)
json_output  # unused variable (src/donkey_kit/llm/catalog.py)
is_heuristic  # unused variable (src/donkey_kit/llm/catalog.py)
display_name  # unused variable (src/donkey_kit/llm/catalog.py)
capabilities  # unused variable (src/donkey_kit/llm/catalog.py)
_.list_models  # unused method (src/donkey_kit/llm/client.py)
query  # unused variable (src/donkey_kit/registry/exchange.py)
asset_types  # unused variable (src/donkey_kit/registry/exchange.py)
domain  # unused variable (src/donkey_kit/registry/exchange.py)
_.resolve_mcp  # unused method (src/donkey_kit/registry/exchange.py)
_.resolve_agent  # unused method (src/donkey_kit/registry/exchange.py)
_.explain  # unused method (src/donkey_kit/registry/exchange.py)
_.warm  # unused method (src/donkey_kit/registry/exchange.py)
_.refresh  # unused method (src/donkey_kit/registry/exchange.py)
require_api_instance  # unused variable (src/donkey_kit/registry/governance.py)
require_deployed  # unused variable (src/donkey_kit/registry/governance.py)
require_any_policy  # unused variable (src/donkey_kit/registry/governance.py)
required_policies  # unused variable (src/donkey_kit/registry/governance.py)
forbidden_policies  # unused variable (src/donkey_kit/registry/governance.py)
require_governance_pass  # unused variable (src/donkey_kit/registry/governance.py)
require_gateways  # unused variable (src/donkey_kit/registry/governance.py)
require_tags  # unused variable (src/donkey_kit/registry/governance.py)
require_lifecycle  # unused variable (src/donkey_kit/registry/governance.py)
_.reasons_failed  # unused method (src/donkey_kit/registry/governance.py)
derive_descriptor  # unused function (src/donkey_kit/registry/introspect.py)
entrypoint  # unused variable (src/donkey_kit/registry/introspect.py)
exchange_url  # unused variable (src/donkey_kit/registry/models.py)
_.coordinates  # unused property (src/donkey_kit/registry/models.py)
endpoint_url  # unused variable (src/donkey_kit/registry/models.py)
auth_required  # unused variable (src/donkey_kit/registry/models.py)
skills  # unused variable (src/donkey_kit/registry/models.py)
MCP_SERVER  # unused variable (src/donkey_kit/registry/publication.py)
A2A_AGENT  # unused variable (src/donkey_kit/registry/publication.py)
AGENT  # unused variable (src/donkey_kit/registry/publication.py)
API  # unused variable (src/donkey_kit/registry/publication.py)
FROM_PACKAGE  # unused variable (src/donkey_kit/registry/publication.py)
SEMANTIC_AUTO  # unused variable (src/donkey_kit/registry/publication.py)
email  # unused variable (src/donkey_kit/registry/publication.py)
asset_type  # unused variable (src/donkey_kit/registry/publication.py)
contact  # unused variable (src/donkey_kit/registry/publication.py)
docs  # unused variable (src/donkey_kit/registry/publication.py)
governance  # unused variable (src/donkey_kit/registry/publication.py)
version_strategy  # unused variable (src/donkey_kit/registry/publication.py)
_.preview  # unused method (src/donkey_kit/registry/publication.py)
_.export  # unused method (src/donkey_kit/registry/publication.py)
_.verify  # unused method (src/donkey_kit/registry/publication.py)
raise_on_drift  # unused variable (src/donkey_kit/registry/publication.py)
_.langgraph  # unused method (src/donkey_kit/tools/session.py)
_.adk  # unused method (src/donkey_kit/tools/session.py)
_.strands  # unused method (src/donkey_kit/tools/session.py)
_.llamaindex  # unused method (src/donkey_kit/tools/session.py)
_.crewai  # unused method (src/donkey_kit/tools/session.py)
_.agent_framework  # unused method (src/donkey_kit/tools/session.py)
# The donkey CLI (#730): typer calls the callback and passes the blocked
# command's option by name.
_global  # unused function (src/donkey_kit/cli/_app.py)
if_changed  # unused variable (src/donkey_kit/cli/_blocked.py)
# DonkeyConfig.environment (ANYPOINT_ENV) is public config callers read; it is
# also a keyword of the blocked registry search stubs. Its only in-tree reader
# was the deleted governance.py (#730).
environment  # unused variable (src/donkey_kit/core/config.py, src/donkey_kit/registry/exchange.py)
# Keyword of the blocked publish_if_changed stub (BG §2.5).
publication  # unused variable (src/donkey_kit/registry/publication.py)
